_display_fields: &_display_fields
  display_fields:
    - key: status
      belongs_to: Status
      web: sync_only
    - key: display_type
      belongs_to: DisplayConfig
      column: type_key
      web: sync_only
    - key: model_number
    - key: publish_to_web
      search_as: select
      web: false
    - key: publish_to_erp
      search_as: select
      web: false
    - key: source_model_number
      web: false
    - key: source
      belongs_to: DisplaySource
      web: false
    - key: colors
      search: false
    - key: backlight_type
      belongs_to: true
    - key: viewing_direction
      belongs_to: true
      description: 12 O'Clock, etc
    - key: viewing_cone
    - key: active_area
      dimension: active_area_width_mm, active_area_height_mm
      search: false
    - key: active_area_width_mm
      name: Width
    - key: active_area_height_mm
      name: Height
    - key: backlight_color
      belongs_to: Color
    - key: background_color
      belongs_to: Color
    - key: bonding_type
      belongs_to: true
    - key: digit_height_mm
      search: false
    - key: module_dimensions
      dimension: module_width_mm, module_height_mm, module_thickness_mm
      units_short: mm
    - key: module_width_mm
      name: Width
      search_range: ModuleWidthRange
    - key: module_height_mm
      name: Height
      search_range: ModuleHeightRange
    - key: module_thickness_mm
      name: Thickness
      search_range: ModuleThicknessRange
    - key: module_diagonal_in
      name: Diagonal
      search_range: ModuleDiagonalRange
    - key: no_of_pins
      search: false
    - key: contrast_ratio
      search: false
    - key: resolution
      dimension: resolution_x, resolution_y
      table_name: Reso-lution
    - key: resolution_x
      name: X
      search_range: ResolutionRange
    - key: resolution_y
      name: Y
      search_range: ResolutionRange
    - key: viewing_area
      dimension: viewing_width_mm, viewing_height_mm
      search: false
    - key: viewing_width_mm
      name: Width
    - key: viewing_height_mm
      name: Height
    - key: touch_panel_type
      belongs_to: true
    - key: pixel_color
      belongs_to: Color
    - key: display_mode
      belongs_to: true
      description: TV vs STN, etc
    - key: display_image
      belongs_to: true
      description: Positive vs Negative
    - key: polarizer_mode
      belongs_to: true
    - key: operational_temperature
      name: Operational Temperature (°C)
      table_name: Operational Temp (°C)
      dimension: operational_temperature_min, operational_temperature_max
      units_short: °C
    - key: operational_temperature_min
      name: Min
      search_range: LowTemperatureRange
    - key: operational_temperature_max
      name: Max
      search_range: HighTemperatureRange
    - key: storage_temperature
      name: Storage Temperature (°C)
      dimension: storage_temperature_min, storage_temperature_max
      units_short: °C
    - key: storage_temperature_min
      name: Min
      search_range: LowTemperatureRange
    - key: storage_temperature_max
      name: Max
      search_range: HighTemperatureRange
    - key: character_resolution
      dimension: character_columns, character_rows
      table_name: Char Reso-lution
    - key: character_columns
      name: Cols
      search_range: true
    - key: character_rows
      name: Rows
      search_range: true
    - key: character_type
      belongs_to: true
    - key: luminance_nits
    - key: target_environment
      belongs_to: true
    - key: logic_operating_voltage
      search_range: true
      name: Logic Operating Voltage
    - key: integrated_controller
    - key: interface_types
      has_many: InterfaceType
    - key: total_power_consumption
      search_range: PowerConsumptionRange
      units: Watts
      units_short: W
    - key: icon_type
      belongs_to: true
    - key: mask_type
      belongs_to: true
      search: false
    - key: standard_classification
      belongs_to: true
    - key: comments
      search_as: string
    - key: field_of_view
      search_range: true
      units_short: &deg;
    - key: datasheet
      attachment: pdf
      web: sync_only
    - key: datasheet_public
      web: sync_only
      search_as: select
    - key: specification
      attachment: pdf
      web: sync_only
    - key: source_specification
      attachment: pdf
      web: sync_only
    - key: drawing
      attachment: image
      web: sync_only

display_types: &_display_types
  display_types:
    - key: tft_displays
      tab_names: TFT
      name: Digital TFT Display
      fields: status, display_type, model_number, publish_to_web, publish_to_erp, bonding_type, module_diagonal_in, module_dimensions, viewing_area, active_area, resolution, active_area, backlight_type, operational_temperature, storage_temperature, interface_types, colors, touch_panel_type, viewing_cone, datasheet, datasheet_public, specification, source_specification, drawing, luminance_nits
      web_list: model_number, module_diagonal_in, module_dimensions, active_area, resolution, active_area, backlight_type, operational_temperature, storage_temperature, interface_types, colors, touch_panel_type, luminance_nits
      m2m_group_code: TFTS
      m2m_product_class: TFTS
    - key: glass_displays
      aliases: Display::GlassDisplay
      tab_names: Glass
      name: Glass Display
      fields: status, display_type, model_number, publish_to_web, publish_to_erp, character_resolution, character_type, pixel_color, display_mode, module_dimensions, viewing_area, active_area, digit_height_mm, polarizer_mode, no_of_pins, operational_temperature, datasheet, datasheet_public, specification, source_specification, drawing
      web_list: model_number, character_resolution, display_mode, module_dimensions, digit_height_mm, polarizer_mode, no_of_pins, operational_temperature
      m2m_group_code: GLASS
      m2m_product_class: GLASS
    - key: graphic_module_displays
      tab_names: Graphic Displays
      name: Graphic Display
      fields: status, display_type, model_number, publish_to_web, publish_to_erp, resolution, bonding_type, pixel_color, display_mode, module_dimensions, viewing_area, active_area, display_mode, polarizer_mode, backlight_type, backlight_color, operational_temperature, storage_temperature, datasheet, datasheet_public, specification, source_specification, drawing
      web_list: model_number, resolution, bonding_type, pixel_color, display_mode, module_dimensions, viewing_area, display_mode, polarizer_mode, backlight_type, backlight_color, operational_temperature, storage_temperature, datasheet, datasheet_public, specification, source_specification, drawing
      m2m_group_code: MOD
      m2m_product_class: MODULES
    - key: character_module_displays
      tab_names: Character Modules
      name: Character Module Display
      fields: status, display_type, model_number, publish_to_web, publish_to_erp, character_resolution, character_type, bonding_type, pixel_color, display_mode, module_dimensions, viewing_area, active_area, display_mode, polarizer_mode, backlight_type, backlight_color, operational_temperature, storage_temperature, datasheet, datasheet_public, specification, source_specification, drawing
      web_list: model_number, character_resolution, bonding_type, pixel_color, display_mode, module_dimensions, viewing_area, display_mode, polarizer_mode, backlight_type, backlight_color, operational_temperature, storage_temperature, datasheet, datasheet_public, specification, source_specification, drawing
      m2m_group_code: MOD
      m2m_product_class: MODULES
    - key: oled_displays
      aliases: Display::OledDisplay
      tab_names: OLED
      name: OLED Display
      fields: display_type, model_number, publish_to_web, publish_to_erp, module_diagonal_in, module_dimensions, resolution, colors, active_area, interface_types
      m2m_group_code: OLEDS
      m2m_product_class: OLEDS
    - key: shutters
      fields: status, display_type, model_number, publish_to_web, publish_to_erp, active_area, backlight_type, backlight_color, bonding_type, character_resolution, colors, display_image, pixel_color, luminance_nits, module_dimensions, no_of_pins, operational_temperature, polarizer_mode, storage_temperature, display_mode, viewing_direction, datasheet, datasheet_public, specification, source_specification, drawing
      m2m_group_code: OTHER
      m2m_product_class: ACCESSORIES
      
    - key: module_displays
      deprecated: yup
    - key: sunlight_tft_displays
      deprecated: yup
    - key: small_tft_displays
      deprecated: yup
  
shared_config: &shared_config
  company_name: LXD Research & Display
  <<: *_display_fields
  <<: *_display_types
    
<% local_config = File.join(Doogle::Engine.root, 'config/doogle_config_local.yml') %>
<% if File.exists?(local_config) %>
<%= File.open(local_config).read %>
<% else %>
local_config: &local_config
  nothing: here
<% end %>

development:
  <<: *local_config
  <<: *shared_config
  s3_bucket: 'lxd-ds'
  # s3_bucket: 'lxd-devds'
  
production:
  <<: *local_config
  <<: *shared_config
  s3_bucket: 'lxd-ds'
  
test:
  <<: *local_config
  <<: *shared_config
