_display_fields: &_display_fields
  display_fields:
    - key: display_type
      belongs_to: DisplayConfig
      column: type_key
    - key: status
      belongs_to: Status
    - key: model_number
    - key: source_model_number
      web: false
    - key: source
      belongs_to: DisplaySource
      web: false
    - key: colors
      search: false
    - key: backlight_type
      belongs_to: true
    - key: viewing_direction
      belongs_to: true
      description: 12 O'Clock, etc
    - key: viewing_cone
    - key: active_area
      dimension: active_area_width_mm, active_area_height_mm
      search: false
    - key: active_area_width_mm
      label: Width
    - key: active_area_height_mm
      label: Height
    - key: backlight_color
      belongs_to: Color
    - key: background_color
      belongs_to: Color
    - key: bonding_type
      belongs_to: true
    - key: digit_height
      search: false
    - key: module_dimensions
      dimension: module_width_mm, module_height_mm, module_thickness_mm
      units_short: mm
    - key: module_width_mm
      label: Width
      search_range: ModuleWidthRange
    - key: module_height_mm
      label: Height
      search_range: ModuleHeightRange
    - key: module_thickness_mm
      label: Thickness
      search_range: ModuleThicknessRange
    - key: number_of_pins
      search: false
    - key: contrast_ratio
      search: false
    - key: resolution
      dimension: resolution_x, resolution_y
    - key: resolution_x
      label: X
      search_range: ResolutionRange
    - key: resolution_y
      label: Y
      search_range: ResolutionRange
    - key: viewing_area
      dimension: viewing_width_mm, viewing_height_mm
      search: false
    - key: viewing_width_mm
      label: Width
    - key: viewing_height_mm
      label: Height
    - key: touch_panel_type
      belongs_to: true
    - key: pixel_color
      belongs_to: Color
    - key: display_mode
      belongs_to: true
      description: TV vs STN, etc
    - key: display_image
      belongs_to: true
      description: Positive vs Negative
    - key: polarizer_mode
      belongs_to: true
    - key: operational_temperature
      label: Operational Temperature (째C)
      dimension: operational_temperature_min, operational_temperature_max
      units_short: 째C
    - key: operational_temperature_min
      label: Min
      search_range: LowTemperatureRange
    - key: operational_temperature_max
      label: Max
      search_range: HighTemperatureRange
    - key: storage_temperature
      label: Storage Temperature (째C)
      dimension: storage_temperature_min, storage_temperature_max
      units_short: 째C
    - key: storage_temperature_min
      label: Min
      search_range: LowTemperatureRange
    - key: storage_temperature_max
      label: Max
      search_range: HighTemperatureRange
    - key: character_resolution
      dimension: character_columns, character_rows
    - key: character_columns
      label: Cols
      search_range: true
    - key: character_rows
      label: Rows
      search_range: true
    - key: character_type
      belongs_to: true
    - key: luminance_nits
    - key: target_environment
      belongs_to: true
    - key: logic_operating_voltage
      search_range: true
      label: Logic Operating Voltage
    - key: integrated_controller
    - key: interface_types
      has_many: InterfaceType
    - key: total_power_consumption
      search_range: PowerConsumptionRange
      units: Watts
      units_short: W
    - key: icon_type
      belongs_to: true
    - key: mask_type
      belongs_to: true
      search: false
    - key: standard_classification
      belongs_to: true
    - key: comments
      search_as: string
    - key: field_of_view
      search_range: true
      units_short: &deg;

display_types: &_display_types
  display_types:
    - key: tft_displays
      tab_names: TFT
      name: Digital TFT Display
      fields: display_type, model_number, bonding_type, module_dimensions, viewing_area, active_area, resolution, active_area, backlight_type, operational_temperature, storage_temperature, interface_types, colors, touch_panel_type, viewing_cone
    - key: glass_displays
      aliases: Display::GlassDisplay
      tab_names: Glass
      name: Glass Display
      fields: display_type, model_number, character_resolution, pixel_color, display_mode, module_dimensions, viewing_area, active_area, digit_height, polarizer_mode, number_of_pins, operational_temperature
    - key: graphic_module_displays
      tab_names: Graphic Displays
      name: Graphic Display
      fields: display_type, model_number, resolution, bonding_type, pixel_color, display_mode, module_dimensions, viewing_area, active_area, display_mode, polarizer_mode, backlight_type, backlight_color, operational_temperature, storage_temperature, backlight_type
    - key: character_module_displays
      tab_names: Character Modules
      name: Character Module Display
      fields: display_type, model_number, character_resolution, bonding_type, pixel_color, display_mode, module_dimensions, viewing_area, active_area, display_mode, polarizer_mode, backlight_type, backlight_color, operational_temperature, storage_temperature, backlight_type
    - key: oled_displays
      aliases: Display::OledDisplay
      tab_names: OLED
      name: OLED Display
      fields: display_type, model_number, module_dimensions, resolution, colors, active_area, interface_types
    - key: shutters
      fields: display_type, active_area, backlight_type, backlight_color, bonding_type, character_resolution, colors, display_image, pixel_color, luminance_nits, model_number, module_dimensions, number_of_pins, operational_temperature, polarizer_mode, storage_temperature, display_mode, viewing_direction

    - key: module_displays
      deprecated: yup
    - key: sunlight_tft_displays
      deprecated: yup
    - key: small_tft_displays
      deprecated: yup
  
shared_config: &shared_config
  company_name: LXD Research & Display
  <<: *_display_fields
  <<: *_display_types
    
<% local_config = File.join(Doogle::Engine.root, 'config/doogle_config_local.yml') %>
<% if File.exists?(local_config) %>
<%= File.open(local_config).read %>
<% else %>
local_config: &local_config
  nothing: here
<% end %>

development:
  <<: *local_config
  <<: *shared_config
  s3_bucket: 'lxd-ds'
  # s3_bucket: 'lxd-devds'
  
production:
  <<: *local_config
  <<: *shared_config
  s3_bucket: 'lxd-ds'
  
test:
  <<: *local_config
  <<: *shared_config
