_display_fields: &_display_fields
  display_fields:
    - key: source_model_number
      aliases: Manufacturer Part Number
      ignored: true
    - key: ignored
      ignored: true
      aliases: Chip Location, Customer, Customer Use or Application, Brochure
    - key: specification_type
      system: true
    - key: status
      aliases: Status
      system: true
    - key: model_number
      aliases:
    - key: diagonal_size
      aliases: Diagonal Size
    - key: colors
      aliases:
    - key: panel_size
      aliases:
    - key: dot_format
      aliases:
    - key: dot_size
      aliases:
    - key: dot_pitch
      aliases:
    - key: thickness
      aliases:
    - key: integrated_circuit
      aliases:
    - key: brightness
      aliases: Brightness
    - key: contrast
      aliases:
    - key: backlight_type
      aliases:
    - key: viewing_angle
      aliases:
    - key: operational_temperature
      aliases: Operational Temperature (°C)
    - key: storage_temperature
      aliases: Storage Temperature (°C)
    - key: interface
      aliases:
    - key: active_area
      aliases:
    - key: backlight_color
      aliases:
    - key: bonding_type
      aliases:
    - key: configuration
      aliases: Configuration
    - key: controller
      aliases:
    - key: digit_height
      aliases:
    - key: lcd_type
      aliases:
    - key: module_dimensions
      aliases:
    - key: number_of_digits
      aliases:
    - key: number_of_pins
      aliases:
    - key: operating_voltage
      aliases:
    - key: outline_dimensions
      aliases:
    - key: pixel_configuration
      aliases: Pixel Configuration
    - key: polarizer_mode
      aliases:
    - key: power_consumption
      aliases:
    - key: resolution
      aliases:
    - key: technology_type
      aliases: Technology Type
    - key: view_direction
      aliases:
    - key: viewing_dimensions
      aliases:
    - key: weight
      aliases:
    - key: touch_panel_type
      aliases:
    - key: timing_controller_type
      aliases:

display_types: &_display_types
  display_types:
    - key: tft_displays
      aliases: digital_tft_displays, analog_tft_displays, Display::DigitalTftDisplay, Display::AnalogTftDisplay
      tab_names: TFT
      name: Digital TFT Display
      fields: model_number, diagonal_size, resolution, active_area, outline_dimensions, backlight_type, operational_temperature, storage_temperature, interface, colors, touch_panel_type, timing_controller_type
    - key: sunlight_tft_displays
      tab_names: Sunlight TFT
      name: Sunlight-Readable TFT Display
      fields: model_number, diagonal_size, resolution, active_area, outline_dimensions, backlight_type, interface, colors, touch_panel_type, brightness, viewing_angle
    - key: small_tft_displays
      aliases: Display::SmallTftDisplay
      tab_names: Small TFT
      name: Small Portable TFT Display
      fields: model_number, diagonal_size, resolution, active_area, outline_dimensions, backlight_type, operational_temperature, storage_temperature, interface, colors, touch_panel_type
    - key: glass_displays
      aliases: Display::GlassDisplay
      tab_names: Glass
      name: Glass Display
      fields: model_number, number_of_digits, technology_type, module_dimensions, digit_height, polarizer_mode, number_of_pins, operational_temperature
    - key: module_displays
      aliases: Display::ModuleDisplay
      tab_names: Module
      name: Module Display
      fields: model_number, configuration, lcd_type, technology_type, module_dimensions, viewing_dimensions, polarizer_mode, backlight_type, backlight_color, operational_temperature, storage_temperature
    - key: oled_displays
      aliases: Display::OledDisplay
      tab_names: OLED
      name: OLED Display
      fields: model_number, diagonal_size, pixel_configuration, colors, panel_size, active_area, interface
  
shared_config: &shared_config
  company_name: LXD Research & Display
  <<: *_display_fields
  <<: *_display_types
    
<% local_config = File.join(Doogle::Engine.root, 'config/doogle_config_local.yml') %>
<% if File.exists?(local_config) %>
<%= File.open(local_config).read %>
<% else %>
local_config: &local_config
  nothing: here
<% end %>

development:
  <<: *local_config
  <<: *shared_config
  s3_bucket: 'lxd-ds'
  # s3_bucket: 'lxd-devds'
  
production:
  <<: *local_config
  <<: *shared_config
  s3_bucket: 'lxd-ds'
  
test:
  <<: *local_config
  <<: *shared_config
