_display_fields: &_display_fields
  display_fields:
    - key: status
      belongs_to: Status
      web: true
      search_options: true
      search_include_blank: false
      edit_include_blank: false
    - key: display_type
      belongs_to: DisplayConfig
      db_value: type_key
      web: true
      name: Type
      search_include_blank: false
      edit_include_blank: false
    - key: model_number
    - key: previous_revision_id
      name: Previous Revision
      web: false
      search: false
    - key: erp_id
      web: false
      search: false
      name: ERP Item
    - key: description
    - key: source_model_number
      name: Vendor Part Number
      web: false
    - key: search_vendor
      name: Vendors
      web: false
      editable: false
      belongs_to: SearchVendors
      search_value: search_vendor_id
    - key: vendor_part_number
      name: Vendor Part Number
      web: false
      editable: false
      search_as: string
    - key: display_component_vendor_name
      name: Display Component Vendor Name
      web: false
      search_belongs_to: SearchDisplayComponentVendors
      search_input: display_component_vendor_name
    - key: display_component_model_number
      name: Display Component Model Number
      web: false
    - key: touch_panel_component_vendor_name
      name: Touch Panel Component Vendor Name
      web: false
      search_belongs_to: SearchTouchPanelComponentVendors
      search_input: touch_panel_component_vendor_name
    - key: touch_panel_component_model_number
      name: Touch Panel Component Model Number
      web: false
    - key: original_customer_name
      name: Original Customer
      web: false
    - key: original_customer_part_number
      name: Original Customer P/N
      web: false
    - key: publish_to_web
      search_as: select
      web: false
    - key: on_master_list
      search_as: select
      web: false
      search_as: select
    - key: publish_to_erp
      search_as: select
      web: false
    - key: tft_type
      name: TFT Type
      belongs_to: true
      web: false
    - key: touch_panel_type
      belongs_to: true
    - key: colors
    - key: backlight_type
      belongs_to: true
    - key: resolution
      dimension: resolution_x, resolution_y
      table_name: Reso-lution
    - key: resolution_x
      name: X
      # search_range: ResolutionRange      
    - key: resolution_y
      name: Y
      # search_range: ResolutionRange
    - key: module_dimensions
      dimension: module_width_mm, module_height_mm, module_thickness_mm
      units_short: mm
    - key: module_width_mm
      name: Width
      search_range: ModuleWidthRange
    - key: module_height_mm
      name: Height
      search_range: ModuleHeightRange
    - key: module_thickness_mm
      name: Thickness
      search_range: ModuleThicknessRange
    - key: oled_diagonal_in
      name: Diagonal
      search_options: true
      db_value: module_diagonal_in
      sprintf_config: %s"
    - key: tft_diagonal_in
      name: Diagonal
      search_options: true
      db_value: module_diagonal_in
      sprintf_config: %s"
    - key: viewing_area_diagonal
      editable: false
      web: false
      search: false
      renderable: true
      sprintf_config: %s"
    - key: viewing_area
      dimension: viewing_width_mm, viewing_height_mm
      search: false
    - key: viewing_width_mm
      name: Width
    - key: viewing_height_mm
      name: Height
    - key: active_area
      dimension: active_area_width_mm, active_area_height_mm
      search: false
    - key: active_area_width_mm
      name: Width
    - key: active_area_height_mm
      name: Height
    # - key: viewing_cone
    - key: backlight_color
      belongs_to: Color
    - key: background_color
      belongs_to: Color
    - key: bonding_type
      belongs_to: true
    - key: digit_height_mm
      search: false
    - key: no_of_pins
      name: Number of Pins
      search: false
    - key: multiplex_ratio
    - key: contrast_ratio
      search: false
    # - key: pixel_color
    #   belongs_to: Color
    - key: viewing_direction
      belongs_to: true
      description: 12 O'Clock, etc
    - key: display_mode
      belongs_to: true
      description: TN vs STN, etc
    - key: display_image
      belongs_to: true
      description: Positive vs Negative
    - key: polarizer_mode
      belongs_to: true
      description: Reflective, Transmissive, Transflective
    - key: operational_temperature
      name: Operational Temperature (°C)
      table_name: Operational Temp (°C)
      dimension: operational_temperature_min, operational_temperature_max
      units_short: °C
    - key: operational_temperature_min
      name: Min
      search_range: LowTemperatureRange
    - key: operational_temperature_max
      name: Max
      search_range: HighTemperatureRange
    - key: storage_temperature
      name: Storage Temperature (°C)
      dimension: storage_temperature_min, storage_temperature_max
      units_short: °C
    - key: storage_temperature_min
      name: Min
      search_range: LowTemperatureRange
    - key: storage_temperature_max
      name: Max
      search_range: HighTemperatureRange
    - key: character_resolution
      dimension: character_columns, character_rows
      table_name: Char Reso-lution
    - key: character_columns
      name: Cols
      search_range: true
    - key: character_rows
      name: Rows
      search_range: true
    - key: character_type
      belongs_to: true
    - key: luminance_nits
      datasheet_hint: \"typical\" value
      search_range: LuminanceRange
    - key: target_environment
      belongs_to: true
      web: true
    - key: logic_operating_voltage
      search_range: true
      name: Logic Operating Voltage
      datasheet_hint: Typical voltage, or VDD
    - key: integrated_controller
    - key: interface_types
      has_many: InterfaceType
    - key: gamma_required
      search_as: select
      web: false
    - key: total_power_consumption
      search_range: PowerConsumptionRange
      units: Watts
      units_short: W
    - key: icon_type
      belongs_to: true
    - key: mask_type
      belongs_to: true
      search: false
    - key: standard_classification
      belongs_to: true
      web: false
    - key: field_of_view
      search_range: true
      units_short: &deg;
    - key: datasheet
      attachment: pdf
      web: true
      search: false
    - key: datasheet_public
      web: true
      search_as: select
    - key: specification
      attachment: pdf
      web: false
      search: false
    - key: source_specification
      attachment: pdf
      web: false
      name: Non-public Specification
      search: false
    - key: drawing
      name: Web Datasheet
      attachment: pdf
      web: true
      search: false
    - key: comments
      search_as: string
      web: false
    - key: sql_query
      web: false
      renderable: false
      editable: false

display_types: &_display_types
  display_types:
    - key: any
      name: Any
      fields: status, display_type, model_number, search_vendor, vendor_part_number, description, previous_revision_id, erp_id, comments, original_customer_name, original_customer_part_number, standard_classification, publish_to_web, on_master_list, sql_query
      default_search_fields: display_type, model_number, search_vendor, vendor_part_number

    - key: tft_displays
      name: Digital TFT
      fields: status, display_type, model_number, search_vendor, vendor_part_number, description, previous_revision_id, tft_type, erp_id, publish_to_web, on_master_list, bonding_type, polarizer_mode, viewing_direction, tft_diagonal_in, module_dimensions, active_area, resolution, active_area, backlight_type, no_of_pins, operational_temperature, storage_temperature, interface_types, gamma_required, colors, touch_panel_type, datasheet, specification, drawing, luminance_nits, integrated_controller, logic_operating_voltage, target_environment, comments, standard_classification, original_customer_name, original_customer_part_number, sql_query
      default_search_fields: display_type, model_number, search_vendor, tft_diagonal_in, resolution, interface_types
      web_list: model_number, tft_diagonal_in, module_dimensions, active_area, resolution, backlight_type, operational_temperature, storage_temperature, interface_types, colors, touch_panel_type, luminance_nits
      master_list: model_number, search_vendor, vendor_part_number, tft_type, bonding_type, polarizer_mode, tft_diagonal_in, module_dimensions, active_area, resolution, active_area, backlight_type, operational_temperature, storage_temperature, interface_types, gamma_required, colors, touch_panel_type, datasheet, specification, drawing, luminance_nits, integrated_controller, target_environment, comments, standard_classification
      m2m_group_code: TFTS
      m2m_product_class: TFTS
      model_number_prefix: M
      default_description: '#{self.module_diagonal_in.to_f}\" TFT'
      
    - key: segment_glass_displays
      name: Segment Glass Display
      fields: status, display_type, model_number, search_vendor, vendor_part_number, description, previous_revision_id, erp_id, publish_to_web, on_master_list, character_resolution, character_type, display_mode, viewing_direction, module_dimensions, viewing_area, active_area, digit_height_mm, polarizer_mode, display_image, no_of_pins, operational_temperature, datasheet, specification, drawing, comments, standard_classification, multiplex_ratio, original_customer_name, original_customer_part_number, sql_query
      default_search_fields: display_type, model_number, character_resolution, display_mode
      web_list: model_number, character_resolution, display_mode, module_dimensions, digit_height_mm, polarizer_mode, no_of_pins, operational_temperature
      master_list: model_number, search_vendor, vendor_part_number, character_resolution, character_type, display_mode, viewing_direction, module_dimensions, viewing_area, active_area, digit_height_mm, polarizer_mode, display_image, no_of_pins, operational_temperature, datasheet, specification, comments, standard_classification, multiplex_ratio, original_customer_name
      m2m_group_code: GLASS
      m2m_product_class: GLASS
      model_number_prefix: H
      default_description: '#{clean_decimal(self.character_columns)} x #{clean_decimal(self.character_rows)} Character Glass'
      
    - key: graphic_glass_displays
      fields: status, display_type, model_number, search_vendor, vendor_part_number, description, previous_revision_id, erp_id, publish_to_web, on_master_list, viewing_direction, resolution, module_dimensions, viewing_area, active_area, display_mode, polarizer_mode, display_image, operational_temperature, storage_temperature, datasheet, specification, drawing, comments, standard_classification, multiplex_ratio, original_customer_name, original_customer_part_number, sql_query
      default_search_fields: display_type, model_number, resolution, display_mode
      web_list: model_number, resolution, module_dimensions, viewing_area, display_mode, polarizer_mode, operational_temperature, storage_temperature, datasheet
      master_list: display_type, model_number, search_vendor, vendor_part_number, viewing_direction, resolution, module_dimensions, viewing_area, active_area, display_mode, polarizer_mode, display_image, operational_temperature, storage_temperature, datasheet, specification, drawing, comments, standard_classification, multiplex_ratio, original_customer_name
      m2m_group_code: GLASS
      m2m_product_class: GLASS
      model_number_prefix: H
      default_description: '#{self.resolution_x} x #{self.resolution_y} Graphics Glass'
      
    - key: graphic_module_displays
      name: Graphic Module
      fields: status, display_type, model_number, search_vendor, vendor_part_number, description, previous_revision_id, erp_id, publish_to_web, on_master_list, viewing_direction, logic_operating_voltage, resolution, bonding_type, module_dimensions, viewing_area, viewing_area_diagonal, active_area, display_mode, polarizer_mode, display_image, backlight_type, backlight_color, operational_temperature, storage_temperature, interface_types, integrated_controller, datasheet, specification, drawing, comments, standard_classification, touch_panel_type, original_customer_name, original_customer_part_number, sql_query
      default_search_fields: display_type, model_number, resolution, bonding_type, display_mode
      web_list: model_number, resolution, bonding_type, module_dimensions, viewing_area, display_mode, polarizer_mode, backlight_type, backlight_color, operational_temperature, storage_temperature, datasheet
      master_list: display_type, model_number, search_vendor, vendor_part_number, viewing_direction, logic_operating_voltage, resolution, bonding_type, module_dimensions, viewing_area, viewing_area_diagonal, active_area, display_mode, polarizer_mode, display_image, backlight_type, backlight_color, operational_temperature, storage_temperature, interface_types, integrated_controller, datasheet, specification, drawing, comments, standard_classification, touch_panel_type, original_customer_name
      m2m_group_code: MOD
      m2m_product_class: MODULES
      model_number_prefix: M
      default_description: '#{self.resolution_x} x #{self.resolution_y} Graphics Module'
      
    - key: character_module_displays
      name: Segmented Module
      fields: status, display_type, model_number, search_vendor, vendor_part_number, description, previous_revision_id, erp_id, publish_to_web, on_master_list, viewing_direction, logic_operating_voltage, character_resolution, character_type, bonding_type, display_mode, module_dimensions, viewing_area, active_area, polarizer_mode, display_image, backlight_type, backlight_color, operational_temperature, storage_temperature, interface_types, integrated_controller, datasheet, specification, drawing, comments, standard_classification, original_customer_name, original_customer_part_number, sql_query
      default_search_fields: display_type, model_number, character_resolution, bonding_type, display_mode
      web_list: model_number, character_resolution, bonding_type, module_dimensions, viewing_area, display_mode, polarizer_mode, backlight_type, backlight_color, operational_temperature, storage_temperature, datasheet
      master_list: display_type, model_number, search_vendor, vendor_part_number, viewing_direction, logic_operating_voltage, character_resolution, character_type, bonding_type, display_mode, module_dimensions, viewing_area, active_area, polarizer_mode, display_image, backlight_type, backlight_color, operational_temperature, storage_temperature, interface_types, integrated_controller, datasheet, specification, drawing, comments, standard_classification, original_customer_name
      m2m_group_code: MOD
      m2m_product_class: MODULES
      model_number_prefix: M
      default_description: '#{clean_decimal(self.character_columns)} x #{clean_decimal(self.character_rows)} Character Module'
      
    - key: oled_displays
      name: OLED Graphic Module
      fields: status, display_type, model_number, search_vendor, vendor_part_number, description, previous_revision_id, erp_id, publish_to_web, on_master_list, oled_diagonal_in, module_dimensions, resolution, colors, active_area, interface_types, comments, standard_classification, touch_panel_type, datasheet, specification, drawing, original_customer_name, original_customer_part_number, sql_query
      default_search_fields: display_type, model_number, search_vendor, resolution, module_dimensions
      web_list: display_type, model_number, oled_diagonal_in, module_dimensions, resolution, colors, active_area, interface_types
      master_list: model_number, search_vendor, vendor_part_number, oled_diagonal_in, module_dimensions, resolution, colors, active_area, interface_types, comments, standard_classification, touch_panel_type, datasheet, specification
      m2m_group_code: OLEDS
      m2m_product_class: OLEDS
      model_number_prefix: L
      default_description: '#{self.module_diagonal_in.to_f}\" OLED'

    - key: oled_character_modules
      name: OLED Character Module
      fields: status, display_type, model_number, search_vendor, vendor_part_number, description, previous_revision_id, erp_id, publish_to_web, on_master_list, oled_diagonal_in, module_dimensions, character_resolution, colors, active_area, interface_types, comments, standard_classification, touch_panel_type, datasheet, specification, drawing, original_customer_name, original_customer_part_number, sql_query
      default_search_fields: display_type, model_number, search_vendor, character_resolution, module_dimensions
      web_list: display_type, model_number, oled_diagonal_in, module_dimensions, character_resolution, colors, active_area, interface_types
      master_list: display_type, model_number, search_vendor, vendor_part_number, description, oled_diagonal_in, module_dimensions, character_resolution, colors, active_area, interface_types, comments, standard_classification, touch_panel_type, datasheet, specification, drawing
      m2m_group_code: OLEDS
      m2m_product_class: OLEDS
      model_number_prefix: L
      default_description: '#{clean_decimal(self.character_columns)} x #{clean_decimal(self.character_rows)} OLED'
      
    - key: accessories
      fields: status, display_type, search_vendor, vendor_part_number, model_number, description, previous_revision_id, erp_id, datasheet, specification, drawing, comments, original_customer_name, original_customer_part_number, sql_query
      master_list: display_type, search_vendor, vendor_part_number, model_number, description, datasheet, specification, drawing, comments, original_customer_name
      default_search_fields: display_type, model_number, description
      m2m_group_code: OTHER
      m2m_product_class: ACCESSORIES
      model_number_prefix: A
      default_description: Accessory
      
    - key: shutter
      name: Shutter
      fields: status, display_type, search_vendor, vendor_part_number, model_number, description, previous_revision_id, erp_id, module_dimensions, datasheet, datasheet_public, drawing, specification, comments, original_customer_name, original_customer_part_number, sql_query
      master_list: display_type, search_vendor, vendor_part_number, model_number, description, module_dimensions, datasheet, specification, drawing, comments, original_customer_name
      default_search_fields: display_type, model_number, description, module_dimensions
      model_number_prefix: H
      m2m_group_code: GLASS
      m2m_product_class: GLASS
      default_description: Shutter
      
shared_config: &shared_config
  <<: *_display_fields
  <<: *_display_types
    
<% local_config = File.join(Doogle::Engine.root, 'config/doogle_config_local.yml') %>
<% if File.exists?(local_config) %>
<%= File.open(local_config).read %>
<% else %>
local_config: &local_config
  nothing: here
<% end %>

development:
  <<: *local_config
  <<: *shared_config
  
production:
  <<: *local_config
  <<: *shared_config
  
test:
  <<: *local_config
  <<: *shared_config
