_display_fields: &_display_fields
  display_fields:
    - key: source_model_number
      aliases: Manufacturer Part Number
      ignored: true
    - key: ignored
      ignored: true
      aliases: Chip Location, Customer, Customer Use or Application, Brochure
    - key: specification_type
      system: true
    - key: status
      aliases: Status
      system: true
    - key: model_number
      aliases:
    - key: colors
      aliases:
    - key: backlight_type
    - key: viewing_angle
    - key: interface
    - key: active_area
      dimension: active_area_width_mm, active_area_height_mm
    - key: active_area_width_mm
      label: Width
    - key: active_area_height_mm
      label: Height
    - key: backlight_color
      collection: Color
    - key: bonding_type
      collection: true
    - key: digit_height
    - key: module_dimensions
      dimension: module_width_mm, module_height_mm, module_thickness_mm
    - key: module_width_mm
      label: Width
    - key: module_height_mm
      label: Height
    - key: module_thickness_mm
      label: Thickness
    - key: number_of_pins
    - key: resolution
      dimension: resolution_x, resolution_y
    - key: resolution_x
      label: X
    - key: resolution_y
      label: Y
    - key: viewing_dimensions
      dimension: viewing_width_mm, viewing_height_mm
    - key: viewing_width_mm
      label: Width
    - key: viewing_height_mm
      label: Height
    - key: touch_panel_type
      collection: true
    - key: timing_controller_type
      collection: true
    - key: filter_color
      collection: Color
    - key: twist_type
      collection: true
    - key: display_mode
      collection: true
    - key: polarizer_mode
      collection: true
    - key: operational_temperature
      aliases: Operational Temperature (°C)
      range: operational_temperature_min, operational_temperature_max
    - key: operational_temperature_min
      label: Min
    - key: operational_temperature_max
      label: Max
    - key: storage_temperature
      aliases: Storage Temperature (°C)
      range: storage_temperature_min, storage_temperature_max
    - key: storage_temperature_min
      label: Min
    - key: storage_temperature_max
      label: Max
    - key: character_resolution
      dimension: character_columns, character_rows
    - key: character_columns
      label: Cols
    - key: character_rows
      label: Rows
    - key: luminance_nits

display_types: &_display_types
  display_types:
    - key: tft_displays
      aliases: digital_tft_displays, analog_tft_displays, Display::DigitalTftDisplay, Display::AnalogTftDisplay
      tab_names: TFT
      name: Digital TFT Display
      fields: model_number, bonding_type, module_dimensions, resolution, active_area, backlight_type, operational_temperature, storage_temperature, interface, colors, touch_panel_type, timing_controller_type
    - key: sunlight_tft_displays
      tab_names: Sunlight TFT
      name: Sunlight-Readable TFT Display
      fields: model_number, bonding_type, module_dimensions, resolution, active_area, backlight_type, interface, colors, touch_panel_type, luminance_nits, viewing_angle
    - key: small_tft_displays
      aliases: Display::SmallTftDisplay
      tab_names: Small TFT
      name: Small Portable TFT Display
      fields: model_number, module_dimensions, resolution, active_area, backlight_type, operational_temperature, storage_temperature, interface, colors, touch_panel_type
    - key: glass_displays
      aliases: Display::GlassDisplay
      tab_names: Glass
      name: Glass Display
      fields: model_number, character_resolution, filter_color, twist_type, module_dimensions, digit_height, polarizer_mode, number_of_pins, operational_temperature
    - key: graphic_module_displays
      tab_names: Graphic Displays
      name: Graphic Display
      fields: model_number, resolution, bonding_type, filter_color, twist_type, module_dimensions, viewing_dimensions, display_mode, polarizer_mode, backlight_type, backlight_color, operational_temperature, storage_temperature, backlight_type
    - key: character_module_displays
      tab_names: Character Modules
      name: Character Module Display
      fields: model_number, character_resolution, bonding_type, filter_color, twist_type, module_dimensions, viewing_dimensions, display_mode, polarizer_mode, backlight_type, backlight_color, operational_temperature, storage_temperature, backlight_type
    - key: oled_displays
      aliases: Display::OledDisplay
      tab_names: OLED
      name: OLED Display
      fields: model_number, module_dimensions, resolution, colors, active_area, interface
    - key: module_displays
  
shared_config: &shared_config
  company_name: LXD Research & Display
  <<: *_display_fields
  <<: *_display_types
    
<% local_config = File.join(Doogle::Engine.root, 'config/doogle_config_local.yml') %>
<% if File.exists?(local_config) %>
<%= File.open(local_config).read %>
<% else %>
local_config: &local_config
  nothing: here
<% end %>

development:
  <<: *local_config
  <<: *shared_config
  s3_bucket: 'lxd-ds'
  # s3_bucket: 'lxd-devds'
  
production:
  <<: *local_config
  <<: *shared_config
  s3_bucket: 'lxd-ds'
  
test:
  <<: *local_config
  <<: *shared_config
